language: ruby
rvm:
- 2.3.3
addons:
  ssh_known_hosts:
    - wolf.uberspace.de
    - 185.26.156.65
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
cache: bundler
script: JEKYLL_ENV=production bundle exec jekyll build && bundle exec htmlproofer ./_site --disable-external
before_deploy:
- openssl aes-256-cbc -K $encrypted_518a90de15e0_key -iv $encrypted_518a90de15e0_iv
  -in deploy_ed25519.enc -out /tmp/deploy_ed25519 -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_ed25519
- ssh-add /tmp/deploy_ed25519
- chmod +x scripts/deploy.sh
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch:
      - master