# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal Website
email: github@2martens.de
description: > # this means to ignore newlines until "baseurl:"
  On this site you can find my political views and other content
  related to me personally.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jim.2martens.de" # the base hostname & protocol for your site
twitter_username: 2martens
github_username:  frmwrk123

# Build settings
markdown: kramdown
