# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 2martens.de
email: github@2martens.de
description: > # this means to ignore newlines until "baseurl:"
  On this site you can find my political views and other content
  related to me personally.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://2martens.de" # the base hostname & protocol for your site
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jim Martens"
      sidebarboxes: "author encrypted-communication"
  -
      scope:
        path: ""
        type: "pages"
      values:
        layout: "page"
        sidebarboxes: "author encrypted-communication"

# Build settings
markdown: kramdown
include:
  - .htaccess
exclude:
  - scripts
  - README.md
  - Gemfile
  - Gemfile.lock
  - deploy_ed25519.enc
  - LICENSE
  - vendor
  - node_modules